---

-  hosts: all
   become: true
   tasks:
   - name: update repository index 
     apt: 
       update_cache: yes

   - name: install the apache software
     apt:
       name: apache2

   - name: update wget app
     apt:
       name: wget
       state: latest
