---

-  hosts: all
   become: true
   tasks:
 #  - name: update repository index 
 #    apt: 
 #      update_cache: yes

   - name: install the apache software
     apt:
       name: apache2
       state: absent

   - name: update wget app
     apt:
       name: wget
       state: absent
